//
//  Questions.swift
//  VGTrivia
//
//  Created by Anne Ferret on 22/08/2025.
//

let questions: [Question] = [
    Question(
        title: "Mario",
        content: "What's the official last name of famous Nintendo's character, **Mario**?",
        answers: ["Mario", "Giamatti", "Letsago", "Toadstool"],
        correctAnswer: "Mario",
        explanation: "This weird last name was coined in the infamous Super Mario Bros. 1993 movie. At first, the maker of Mario, Shigeru Miyamoto, found it rather ridiculous, but in 2015, he admitted that Mario's full name was indeed **\"Mario Mario\"**.",
    ),
    Question(
        title: "Shake it",
        content: "This **1999 rhythm game** features a monkey playing maracas, wearing cliché Latin-American attire...",
        answers: ["Super Monkey Ball", "Samba de Amigo", "Donkey Konga", "Pop'n Music"],
        correctAnswer: "Samba de Amigo",
        explanation: "An arcade game ported to the SEGA Dreamcast, Samba de Amigo let the player shake an **actual pair of maracas** to the rhythm of the music and strike various poses.",
    ),
    Question(
        title: "Blue blur",
        content: "Which year saw the release of the very first **Sonic the Hedgehog** game by SEGA?",
        answers: ["1989", "1991", "1993", "1995"],
        correctAnswer: "1991",
        explanation: "A mere year after Nintendo released their SNES and Super Mario World, Sonic showed that the SEGA Mega Drive (Genesis in the USA), available since 1988 in Japan, was still a powerhouse to be reckoned with.",
        preventShuffling: true,
    ),
    Question(
        title: "Urgh",
        content: "He used (without permission) a music from **Sonic the Hedgehog (2006)** for a commercial...",
        answers: ["Donald Trump", "Jair Bolsonaro", "Vladimir Putin", "Javier Milei"],
        correctAnswer: "Jair Bolsonaro",
        explanation: "The fascist Bolsonaro was exposed by the official **Sonic the Hedgehog Twitter account**, for releasing a commercial prominently featuring an epic boss battle theme stolen from the Sonic the Hedgehog (2006) game soundtrack.",
    ),
    Question(
        title: "Strawberries!",
        content: "2D platformer **Celeste (2018)** actually started as a tiny game jam project on the following platform...",
        answers: ["PICO-8", "Game Boy Color", "NES", "Intellivision Amico"],
        correctAnswer: "PICO-8",
        explanation: "This original version of Celeste was included in the full-fledged version, as a bonus. The **PICO-8** is a \"fantasy\" retro-style console. It feels like a regular console, but runs on Windows, Mac, Linux... ",
    ),
    Question(
        title: "Earworm",
        content: "This studio used to start their games with a resounding **\"Challenge everything\"**...",
        answers: ["EA", "Activision", "SEGA", "Blizzard"],
        correctAnswer: "EA",
        explanation: "Many players remember the whispered sound \"EA Games! Challenge everything\". It lasted only from around 2002 to 2005, but was featured in many iconic games : The Sims 2, Need for Speed Underground, the Battlefield and Harry Potter series...",
    ),
    Question(
        title: "The Wall",
        content: "This game was wildly marketed as a **\"Soviet Game\"** in the West during the late 1980s...",
        answers: ["Tetris", "Missile Command", "Populous", "Castle Wolfenstein"],
        correctAnswer: "Tetris",
        explanation: "Created in 1985, during the last years of the **USSR**. It escaped the iron curtain thanks to more-or-less shady deals. In the West, marketers sold it as a mysterious \"Soviet Mind Game\", complete with faux-cyrillic fonts and Russian iconography.",
    ),
    Question(
        title: "Beep boop",
        content: "Which popular music software is still used nowadays to create tunes on the original **Game Boy**?",
        answers: ["LSDj", "MilkyTracker", "Ableton Live", "Virtual DJ"],
        correctAnswer: "LSDj",
        explanation: "This popular piece of software has been developed and updated by its creator, **Johan Kotlinki**, for more than two decades. It can be put on a blank cartridge and run on the Game Boy hardware, to make chiptune music on-the-go!",
    ),
    Question(
        title: "Iconic is the word",
        content: "This guy is responsible for the original **Super Mario Bros. (1985)** music themes...",
        answers: ["Koji Kondo", "Nobuo Uematsu", "Yuzo Koshiro", "Hirokazu Tanaka"],
        correctAnswer: "Koji Kondo",
        explanation: "**Koji Kondo** has composed music for the Super Mario Bros. and The Legend of Zelda series since their inception, and he's still going to this day. He's kind of a legend.",
    ),
    Question(
        title: "Still Alive",
        content: "🎵 This was a triumph. I'm making a note here... 🎵",
        answers: ["HUGE SUCCESS.", "S.O.S.", "MORNING DRESS.", "WHAT A MESS."],
        correctAnswer: "HUGE SUCCESS.",
        explanation: "Those were the opening lyrics from **Still Alive**, the ending theme of Portal. It was sung by GLaDOS, a fictional AI / supercomputer whose primary function is to kill you, and probably kill you again if she succeeds.",
    ),
    Question(
        title: "The more the merrier",
        content: "This was the first popular home video game console to come with **four controller ports**, instead of usually two...",
        answers: ["Nintendo 64", "PlayStation", "Xbox", "Dreamcast"],
        correctAnswer: "Nintendo 64",
        explanation: "The Nintendo 64 was indeed the first well-known home console to feature four controller ports, making it an ideal candidate for **multiplayer games** (GoldenEye 007, Mario Kart 64, Mario Party, Super Smash Bros...).",
    ),
    Question(
        title: "On the radio",
        content: "Those famous bands all have covers of their music in the fictional language of **The Sims**... almost. Which is the odd one out of the list?",
        answers: ["Coldplay", "The Black Eyed Peas", "Depeche Mode", "Katy Perry"],
        correctAnswer: "Coldplay",
        explanation: "**The Sims** convinced many artists to gibberish their own songs: Depeche Mode, The Black Eyed Peas, Katy Perry, Paramore, Lily Allen, Carly Rae Jepsen, The Pussycat Dolls, Rise Against, OK Go, My Chemical Romance, Charli XCX, girl in red...",
    ),
    Question(
        title: "Soon soon!",
        content: "**The Sims** video game series invented a peculiar language that is used in the game world. How was it named?",
        answers: ["Simlish", "Simmish", "Simsling", "Simspeak"],
        correctAnswer: "Simlish",
        explanation: "A few phrases and words do exist in Simlish, but for the most part, it's gibberish. It does use a **limited set of consonants**, to make it \"sound\" like a real language.",
    ),
    Question(
        title: "Four in a square",
        content: "In **Minecraft (2011)**, you need them to make a crafting table...",
        answers: ["Wooden planks", "Logs", "Stones", "Sticks"],
        correctAnswer: "Wooden planks",
        explanation: "Any sort of wooden plank will do, as long as you have four of them, and put them in a 2x2 square.",
    ),
    Question(
        title: "Now loading...",
        content: "Which of these consoles didn't have a **CD drive**?",
        answers: ["Nintendo 64", "PlayStation", "3DO Interactive Multiplayer", "SEGA Saturn"],
        correctAnswer: "Nintendo 64",
        explanation: "Nintendo was notoriously late to the CD party. The limited cartridge storage of the Nintendo 64 prevented it from getting games with heavy content such as CD-quality music or cinematics.",
    ),
    Question(
        title: "Under the truck",
        content: "What's the **151st Pokémon**...",
        answers: ["Mew", "Pikachu", "Arceus", "Mewtwo"],
        correctAnswer: "Mew",
        explanation: "In the first-generation Pokémon games, it was impossible to get the **hidden 151st Pokémon**, Mew, through normal gameplay. An urban legend claimed that it could be found in the game by triggering a rare event involving a truck. Of course, it was untrue.",
    ),
    Question(
        title: "Friends forever",
        content: "In which game series can you see **Mario**, **Sonic**, **Pikachu** and their friends fighting against each other without mercy?",
        answers: ["Super Smash Bros.", "Super Battle Bros.", "Super VS Bros.", "Super Brawler Bros."],
        correctAnswer: "Super Smash Bros.",
        explanation: "What started as a small party game with twelve Nintendo characters evolved to become an all-star brawler. Its latest installment, Super Smash Bros. Ultimate, features **89 characters** from many different game studios!",
    ),
    Question(
        title: "...come again?",
        content: "Gamers came up with what they called the **Nuzlocke challenge**, a set of rules to make the games of the following series harder to complete...",
        answers: ["Pokémon", "Super Mario Bros.", "Dark Souls", "Final Fantasy"],
        correctAnswer: "Pokémon",
        explanation: "The Nuzlocke challenge was sort of an attempt to make a **hard mode** for Pokémon games. Its most well-known rule forces the player to consider that any K.O'd Pokémon is actually dead: it cannot ever be used again.",
    ),
    Question(
        title: "There's more than 150...",
        content: "Only one of those isn't a Champion from the massive character roaster of **League of Legends (2009)**...",
        answers: ["Bristleback", "Mordekaiser", "Nocturne", "Jinx"],
        correctAnswer: "Bristleback",
        explanation: "Bristleback is actually a character from **Dota 2**, a game bearing striking resemblance to League of Legends. The initial DotA (then a mod for Warcraft III) saw its team split between the two projects and... listen, it's a long story, okay?",
    ),
    Question(
        title: "You can't always get what you want",
        content: "A critical and commercial failure, this console was the lowest-selling hardware of all **Nintendo** history...",
        answers: ["Virtual Boy", "Nintendo Wii U", "Nintendo DSi", "Master System"],
        correctAnswer: "Virtual Boy",
        explanation: "50% VR headset, 50% Game Boy successor, the Virtual Boy was 100% a failure, with only 770,000 units sold worldwide. Nintendo barely acknowledges it ever happened. Its second biggest flop, the Wii U, still sold more than 13 million units.",
    ),
    Question(
        title: "Muscle memory",
        content: "↑ ↑ ↓ ↓ ← → ← → B A START",
        answers: ["Konami code", "PaRappa The Rapper", "Sonic debug", "Lara Croft nude"],
        correctAnswer: "Konami code",
        explanation: "First used in the title screen of **Gradius (1986)** for the NES, to unlock power-ups, the code was then inserted in many Konami games. Other developers started using it, too. Nowadays, it's more of an easter egg, hidden in many games.",
    ),
]
