//
//  Questions.swift
//  VGTrivia
//
//  Created by Anne Ferret on 22/08/2025.
//

let questions: [Question] = [
    Question(
        title: "Mario",
        content: "What's the official last name of famous Nintendo's character, **Mario**?",
        answers: ["Mario", "Giamatti", "Letsago", "Toadstool"],
        correctAnswer: "Mario",
        explanation: "",
    ),
    Question(
        title: "Shake it",
        content: "This **1999 rhythm game** features a monkey playing maracas, wearing cliché Latin-American attire...",
        answers: ["Super Monkey Ball", "Samba de Amigo", "Donkey Konga", "Pop'n Music"],
        correctAnswer: "Samba de Amigo",
        explanation: "",
    ),
    Question(
        title: "Blue blur",
        content: "Which year saw the release of the very first **Sonic the Hedgehog** game by SEGA?",
        answers: ["1991", "1992", "1993", "1994"],
        correctAnswer: "1991",
        explanation: "",
        preventShuffling: true,
    ),
    Question(
        title: "Urgh",
        content: "He used (without permission) a music from **Sonic the Hedgehog (2006)** for a commercial...",
        answers: ["Donald Trump", "Jair Bolsonaro", "Vladimir Putin", "Javier Milei"],
        correctAnswer: "Jair Bolsonaro",
        explanation: "",
    ),
    Question(
        title: "Strawberries!",
        content: "2D platformer **Celeste (2018)** actually started as a tiny game jam project on the following platform...",
        answers: ["PICO-8", "Game Boy Color", "NES", "Intellivision Amico"],
        correctAnswer: "PICO-8",
        explanation: "",
    ),
    Question(
        title: "Earworm",
        content: "This studio used to start their games with a resounding **\"Challenge everything\"**...",
        answers: ["EA", "Activision", "SEGA", "Blizzard"],
        correctAnswer: "EA",
        explanation: "",
    ),
    Question(
        title: "The Wall",
        content: "This game was wildly marketed as a **\"Soviet Game\"** in the West during the late 1980s...",
        answers: ["Tetris", "Missile Command", "Populous", "Castle Wolfenstein"],
        correctAnswer: "Tetris",
        explanation: "",
    ),
    Question(
        title: "Beep boop",
        content: "Which popular music software is still used nowadays to create tunes on the original **Game Boy**?",
        answers: ["LSDj", "MilkyTracker", "Ableton Live", "Virtual DJ"],
        correctAnswer: "LSDj",
        explanation: "",
    ),
    Question(
        title: "Iconic is the word",
        content: "This guy is responsible for the original **Super Mario Bros. (1985)** music themes...",
        answers: ["Koji Kondo", "Nobuo Uematsu", "Yuzo Koshiro", "Hirokazu Tanaka"],
        correctAnswer: "Koji Kondo",
        explanation: "",
    ),
    Question(
        title: "Still Alive",
        content: "🎵 This was a triumph. I'm making a note here... 🎵",
        answers: ["HUGE SUCCESS.", "S.O.S.", "MORNING DRESS.", "WHAT A MESS."],
        correctAnswer: "HUGE SUCCESS.",
        explanation: "",
    ),
    Question(
        title: "The more the merrier",
        content: "This was the first popular home video game console to come with **four controller ports**, instead of usually two...",
        answers: ["Nintendo 64", "PlayStation", "Xbox", "Dreamcast"],
        correctAnswer: "Nintendo 64",
        explanation: "",
    ),
    Question(
        title: "On the radio",
        content: "Those famous bands all have covers of their music in the fictional language of **The Sims**... almost. Which is the odd one out of the list?",
        answers: ["Coldplay", "The Black Eyed Peas", "Depeche Mode", "Katy Perry"],
        correctAnswer: "Coldplay",
        explanation: "",
    ),
    Question(
        title: "Soon soon!",
        content: "**The Sims** video game series invented a peculiar language that is used in the game world. How was it named?",
        answers: ["Simlish", "Simmish", "Simsling", "Simspeak"],
        correctAnswer: "Simlish",
        explanation: "",
    ),
    Question(
        title: "Four in a square",
        content: "In **Minecraft (2011)**, you need them to make a crafting table...",
        answers: ["Wooden planks", "Logs", "Stones", "Sticks"],
        correctAnswer: "Wooden planks",
        explanation: "",
    ),
    Question(
        title: "Now loading...",
        content: "Which of these consoles didn't have a **CD drive**?",
        answers: ["Nintendo 64", "PlayStation", "3DO Interactive Multiplayer", "SEGA Saturn"],
        correctAnswer: "Nintendo 64",
        explanation: "",
    ),
    Question(
        title: "Behind the truck",
        content: "What's the **151st Pokémon**...",
        answers: ["Mew", "Pikachu", "Arceus", "Mewtwo"],
        correctAnswer: "Mew",
        explanation: "",
    ),
    Question(
        title: "Friends forever",
        content: "In which game series can you see **Mario**, **Sonic**, **Pikachu** and their friends fighting against each other without mercy?",
        answers: ["Super Smash Bros.", "Super Battle Bros.", "Super VS Bros.", "Super Brawler Bros."],
        correctAnswer: "Super Smash Bros.",
        explanation: "",
    ),
    Question(
        title: "...come again?",
        content: "Gamers came up with what they called the **Nuzlocke challenge**, a set of rules to make the games of the following series harder to complete...",
        answers: ["Pokémon", "Super Mario Bros.", "Dark Souls", "Final Fantasy"],
        correctAnswer: "Pokémon",
        explanation: "",
    ),
    Question(
        title: "There's more than 150...",
        content: "Only one of those isn't a Champion from the massive character roaster of **League of Legends (2009)**...",
        answers: ["Bristleback", "Mordekaiser", "Nocturne", "Jinx"],
        correctAnswer: "Bristleback",
        explanation: "",
    ),
    Question(
        title: "You can't always get what you want",
        content: "A critical and commercial failure, this console was the lowest-selling hardware of all **Nintendo** history...",
        answers: ["Virtual Boy", "Nintendo Wii U", "Nintendo DSi", "Master System"],
        correctAnswer: "Virtual Boy",
        explanation: "",
    ),
    Question(
        title: "Muscle memory",
        content: "↑ ↑ ↓ ↓ ← → ← → B A START",
        answers: ["Konami code", "PaRappa The Rapper", "Sonic debug", "Lara Croft nude"],
        correctAnswer: "Konami code",
        explanation: "",
    ),
]
